# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    mailer_from: 'bartlomiej.szyszkowski@yellows.eu'
    locale: 'pl'
    app_locales: pl|en|
    uploads_directory: 'user/image'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Adapter\Core\EmailFactory:
        arguments:
            - '%mailer_from%'
        public: true

    email_factory:
        alias: App\Adapter\Core\EmailFactory
        public: true

    doctrine_application_transaction:
        class: App\Adapter\Core\Transaction
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    application_transaction:
            alias: doctrine_application_transaction
            public: true

    App\Adapter\User\Users:
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    Users:
        class: App\Adapter\User\Users
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    App\Entity\User\User\UseCase\CreateUser:
        arguments:
            - "@Users"
            - "@doctrine_application_transaction"

    App\Entity\User\User\UseCase\PasswordReset:
        arguments:
            - "@Users"
            - "@application_transaction"
            - "@email_factory"
        public: true

    App\Entity\User\User\UseCase\PasswordChange:
        arguments:
            - "@Users"
            - "@application_transaction"
            - "@email_factory"
        public: true

    App\Adapter\CandidateProfile\Candidates:
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    Candidates:
        class: App\Adapter\CandidateProfile\Candidates
        arguments:
            - "@doctrine.orm.default_entity_manager"
        public: true

    App\Entity\CandidateProfil\UseCase\CreateCandidateProfile:
        arguments:
            - "@Candidates"
            - "@Users"
            - "@application_transaction"
            - "@email_factory"
            - "@Swift_Mailer"
        public: true

    App\Adapter\Group\Groups:
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    Groups:
        class: App\Adapter\Group\Groups
        arguments:
            - "@doctrine.orm.default_entity_manager"
        public: true

    App\Entity\ActorGrupe\UseCase\CreateActorGroup:
        arguments:
            - "@Groups"
            - "@Users"
            - "@application_transaction"
            - "@email_factory"
            - "@Swift_Mailer"
        public: true

    App\Adapter\BusinessGroupe\BusinessGroup:
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    BusinessGroup:
        class: App\Adapter\BusinessGroupe\BusinessGroup
        arguments:
            - "@doctrine.orm.default_entity_manager"
        public: true

    App\Entity\Business\UseCase\CreateBuisness:
        arguments:
            - "@BusinessGroup"
            - "@Users"
            - "@application_transaction"
            - "@email_factory"
            - "@Swift_Mailer"
    Candidate:
        class: App\Adapter\Candidate\Candidate
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    App\Entity\CandidateProfil\UseCase\EditCandidate:
        arguments:
            - "@Candidate"
            - "@application_transaction"
        public: true

    App\Entity\CandidateProfil\UseCase\ChangePhoto:
        arguments:
            - "@Users"
            - "@application_transaction"
        public: true